package duperr

import (
	"github.com/golangci/plugin-module-register/register"
	"golang.org/x/tools/go/analysis"
)

// The blank import generated by `golangci-lint custom` targets the module
// root, so registration must happen in this package.
//
//nolint:gochecknoinits // module plugins register themselves in init
func init() {
	register.Plugin("duperr", newPlugin)
}

func newPlugin(_ any) (register.LinterPlugin, error) {
	return plugin{}, nil
}

type plugin struct{}

func (plugin) BuildAnalyzers() ([]*analysis.Analyzer, error) {
	return []*analysis.Analyzer{Analyzer}, nil
}

func (plugin) GetLoadMode() string {
	return register.LoadModeTypesInfo
}
