// Code generated by fixturegen. DO NOT EDIT.

package a

import "errors"

// Generated files are skipped entirely: duplicates within them are not
// flagged, and their occurrences don't count toward duplicates elsewhere.
var (
	errGen1 = errors.New("generated duplicate")
	errGen2 = errors.New("generated duplicate")
	errGen3 = errors.New("connecting to db")
)
